const demoApplications = [
  {
    id: "demo-1",
    filmTitle: "Քամու տունը",
    registrationNumber: "CFA-2026-001",
    applicantOrganization: "Արեգակ Ֆիլմ",
    submittedAt: "2026-08-12",
    applicationDeadline: "2026-08-30",
    reviewDeadline: "2026-09-08",
    participationCount: "1-ին մասնակցություն",
    totalBudget: 126000000,
    requestedBudget: 42000000,
    competition: "Խաղարկային լիամետրաժ",
    director: "Անի Մանուկյան",
    subgroup: "Լիամետրաժ դեբյուտային",
    producer: "Դավիթ Սահակյան",
    correctionStatus: "Շտկման ենթակա",
    correctionDeadline: "2026-09-01",
    applicationStatus: "Ուսումնասիրվում է",
  },
  {
    id: "demo-2",
    filmTitle: "Լռության գիծ",
    registrationNumber: "CFA-2026-002",
    applicantOrganization: "Նաիրի Ստուդիա",
    submittedAt: "2026-08-13",
    applicationDeadline: "2026-08-30",
    reviewDeadline: "2026-09-08",
    participationCount: "2-րդ մասնակցություն",
    totalBudget: 54000000,
    requestedBudget: 18000000,
    competition: "Վավերագրական լիամետրաժ",
    director: "Միքայել Գրիգորյան",
    subgroup: "Լիամետրաժ ոչ դեբյուտային",
    producer: "Լիլիթ Կարապետյան",
    correctionStatus: "Շտկված",
    correctionDeadline: "2026-08-27",
    applicationStatus: "Ընդունված",
  },
  {
    id: "demo-3",
    filmTitle: "Փոքր քաղաք",
    registrationNumber: "CFA-2026-003",
    applicantOrganization: "Սեւան Պրոդաքշն",
    submittedAt: "2026-08-15",
    applicationDeadline: "2026-08-30",
    reviewDeadline: "2026-09-08",
    participationCount: "1-ին մասնակցություն",
    totalBudget: 32000000,
    requestedBudget: 9500000,
    competition: "Կարճամետրաժ",
    director: "Նարեկ Դանիելյան",
    subgroup: "Կարճամետրաժ դեբյուտային",
    producer: "Մարիամ Ավագյան",
    correctionStatus: "Չշտկված",
    correctionDeadline: "2026-08-25",
    applicationStatus: "Չընդունված",
  },
  {
    id: "demo-4",
    filmTitle: "Արխիվ 41",
    registrationNumber: "CFA-2026-004",
    applicantOrganization: "Հայկ Դոքս",
    submittedAt: "2026-08-16",
    applicationDeadline: "2026-08-30",
    reviewDeadline: "2026-09-08",
    participationCount: "3-րդ մասնակցություն",
    totalBudget: 78000000,
    requestedBudget: 22000000,
    competition: "Վավերագրական լիամետրաժ",
    director: "Սոնա Պետրոսյան",
    subgroup: "Լիամետրաժ ոչ դեբյուտային",
    producer: "Արամ Խաչատրյան",
    correctionStatus: "Շտկման ենթակա",
    correctionDeadline: "2026-09-03",
    applicationStatus: "Ուսումնասիրվում է",
  },
  {
    id: "demo-5",
    filmTitle: "Հյուսիսային լույս",
    registrationNumber: "CFA-2026-005",
    applicantOrganization: "Լուսանցք Ֆիլմ",
    submittedAt: "2026-08-17",
    applicationDeadline: "2026-08-30",
    reviewDeadline: "2026-09-08",
    participationCount: "4-րդ մասնակցություն",
    totalBudget: 182000000,
    requestedBudget: 55000000,
    competition: "Խաղարկային լիամետրաժ",
    director: "Գոռ Մելքոնյան",
    subgroup: "Լիամետրաժ ոչ դեբյուտային",
    producer: "Էմմա Հովհաննիսյան",
    correctionStatus: "Շտկված",
    correctionDeadline: "2026-08-29",
    applicationStatus: "Ընդունված",
  },
  {
    id: "demo-6",
    filmTitle: "Ձայնի հետքը",
    registrationNumber: "CFA-2026-006",
    applicantOrganization: "ԱրտԲոքս",
    submittedAt: "2026-08-18",
    applicationDeadline: "2026-08-30",
    reviewDeadline: "2026-09-08",
    participationCount: "2-րդ մասնակցություն",
    totalBudget: 24500000,
    requestedBudget: 8000000,
    competition: "Անիմացիոն կարճամետրաժ",
    director: "Ինեսա Ղազարյան",
    subgroup: "Կարճամետրաժ դեբյուտային",
    producer: "Վահե Մուրադյան",
    correctionStatus: "Շտկման ենթակա",
    correctionDeadline: "2026-08-31",
    applicationStatus: "Ուսումնասիրվում է",
  },
  {
    id: "demo-7",
    filmTitle: "Վերադարձ",
    registrationNumber: "CFA-2026-007",
    applicantOrganization: "Կենտրոն Ստուդիո",
    submittedAt: "2026-08-19",
    applicationDeadline: "2026-08-30",
    reviewDeadline: "2026-09-08",
    participationCount: "1-ին մասնակցություն",
    totalBudget: 91000000,
    requestedBudget: 30000000,
    competition: "Խաղարկային լիամետրաժ",
    director: "Արմեն Սիմոնյան",
    subgroup: "Լիամետրաժ դեբյուտային",
    producer: "Լուսինե Մարտիրոսյան",
    correctionStatus: "Չշտկված",
    correctionDeadline: "2026-08-28",
    applicationStatus: "Ուսումնասիրվում է",
  },
  {
    id: "demo-8",
    filmTitle: "Մեկ кадր",
    registrationNumber: "CFA-2026-008",
    applicantOrganization: "Դոկ Լաբ",
    submittedAt: "2026-08-20",
    applicationDeadline: "2026-08-30",
    reviewDeadline: "2026-09-08",
    participationCount: "3-րդ մասնակցություն",
    totalBudget: 18500000,
    requestedBudget: 6500000,
    competition: "Կարճամետրաժ",
    director: "Տաթեւիկ Ներսիսյան",
    subgroup: "Կարճամետրաժ ոչ դեբյուտային",
    producer: "Հովիկ Ասատրյան",
    correctionStatus: "Շտկված",
    correctionDeadline: "2026-09-02",
    applicationStatus: "Ընդունված",
  },
];

export function getDemoApplications() {
  return demoApplications;
}
